name: Авто-нажатие кнопки по воскресеньям

on:
  schedule:
    # Запуск каждое воскресенье в 05:00 UTC (это ровно 08:00 по Московскому времени)
    - cron: '0 5 * * 0'

jobs:
  trigger_button:
    runs-on: ubuntu-latest
    steps:
      - name: Нажимаем кнопку Run workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://github.com{{ github.repository }}/actions/workflows/part1.yml/dispatches \
            -d '{"ref":"main"}'
