name: Авто-нажатие кнопки по воскресеньям

on:
  # Проверка: сработает сегодня (в любой день) в 10:45 UTC (13:45 по МСК)
  schedule:
    - cron: '45 10 * * *'

jobs:
  trigger_button:
    runs-on: ubuntu-latest
    steps:
      - name: Нажимаем кнопку Run workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://github.com{{ github.repository }}/actions/workflows/part1.yml/dispatches \
            -d '{"ref":"main"}'
