name: "Радио Часть 1 (По таймеру - 5 часов)"

on:
  schedule:
    # Запуск каждый день в 18:25 UTC (что равно 21:25 по Московскому времени)
    - cron: '25 18 * * *'
  workflow_dispatch: # Позволяет запускать скрипт вручную кнопкой в интерфейсе

jobs:
  record_part_1:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4

      - name: Установка FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Запись потока (5 часов = 18000 секунд)
        run: |
          ffmpeg -i "https://radio.5-tv.ru/radio.mp3" -t 300 -c copy -f segment -segment_time 300 -strftime 1 "radio_%Y%m%d_%H%M%S.mp3"

      - name: Сохранение аудиофайлов в репозиторий
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add radio_*.mp3
          if ! git diff-index --quiet HEAD; then
            git commit -m "Архив радио. Часть 1 (5 часов) сохранена"
            git push origin HEAD:${{ github.ref }}
          else
            echo "Нет новых файлов для сохранения"
          fi
