name: Радио Часть 1 (Ручной запуск - 5 часов)

on:
  workflow_dispatch: # Запуск только вручную вами по кнопке

jobs:
  record_part_1:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4

      - name: Установка FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Запись потока (5 часов)
        run: |
          ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 5 -i "https://radio.5-tv.ru/radio.mp3" -t 300 -c copy -f segment -segment_time 300 -strftime 1 "radio_%Y%m%d_%H%M%S.mp3"

      - name: Сохранение аудиофайлов в репозиторий
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add radio_*.mp3
          git diff-index --quiet HEAD || git commit -m "Архив радио. Часть 1 (5 часов) сохранена"
          git push

      - name: Автозапуск Части 2
        run: |
          gh workflow run part2.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
